# This is a basic workflow to help you get started with Actions

name: Download Artifact

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_1:
    name: Build and Upload Artificat
    runs-on: ubuntu-latest
    steps:
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: UploadFiles
          path: ${GITHUB_WORKSPACE}/files
          
          
  job_2:
    name: Download Artifact
    needs: [job_1]
    runs-on: ubuntu-latest
    steps:
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: DownloadFiles
          path: ${GITHUB_WORKSPACE}/files

