# This is a basic workflow to help you get started with Actions
# Author : Nikhil Nagesh
name: Workflow-Verify Dep Mgr File

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - '**.md'
      - '**.xml'
      - '**.XML'
      - '**.sh'
      - '.github/**/*'
  pull_request:
    paths-ignore: 
      - '**.md'
      - '**.xml'
      - '**.XML'
      - '**.sh'
      - '.github/**/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Greet
        run: echo Hi There!
         
      # Runs a set of commands using the runners shell
      - name: Validate hms_deployment_manager
        run: |
            arg1=`pwd`
            bash ${GITHUB_WORKSPACE}/shFol/testFile.sh $arg1
