name: "Set Urgent Deployment Label"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Labeler
      uses: actions/labeler@v2
      if: contains(github.event.pull_request.title, 'URGENT')
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
