name: "Set Urgent Deployment Label"
on:
  push:
    branches: [master]
  pull_request:
    paths: 
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Labeler
      uses: actions/labeler@v2
      if: contains(github.event.pull_request.title, 'URGENT')
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
