name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.0
        with:
          title-or-body: "both"
          parameters: '[ {"keywords": ["urgent", "Urgent","emergency"], "labels": ["URG"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
