name: "Set Urgent Deployment Label"
on: 
  pull_request:
    paths: 
      - "**"
jobs:
  LabelUrgent:
    runs-on: ubuntu-latest
    steps:
    - name: LabelerPR
      uses: actions/labeler@v2
      if: contains(github.event.pull_request.title, 'URGENT')
    - name: LabelerPush
      uses: actions/labeler@v2
      if: contains(github.event.push.title, 'URGENT')  
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
