name: "Set Urgent Deployment Label"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Urgency-Labeler
        uses: actions/labeler@v2.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
