name: "Set Urgent Deployment Label"
on:
  pull_request:
    paths: 
      - "**"
jobs:
  LabelPR:
    runs-on: ubuntu-latest
    steps:
      - env:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: LabelerPRCheck1
        uses: actions/labeler@v2
        if: contains(github.event.pull_request.title, 'URGENT')
        with:
          configuration-path: .github/labeler.yml
      - name: LabelerPRCheck2
        uses: actions/labeler@v2
        if: contains(github.event.pull_request.title, 'EMERGENCY')
        with:
          configuration-path: .github/labeler.yml
      - name: LabelerPRCheck3
        uses: actions/labeler@v2
        with:
          configuration-path: .github/labeler.yml
