name: "Label My Name"
on:
  pull_request:
    paths: 
      - "**"
jobs:
  LabelMyName:
    runs-on: ubuntu-latest
    steps:
    - name: Labeler
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labelerMyName.yml
