name: Label PR
on: 
  pull_request:
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Auto Labelling
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/triggerLabel.yml


