name: Label PR
on: 
  pull_request:
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Issue Auto Labeling and Assigning
      uses: Naturalclar/issue-action@v2.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        title-or-body: "both"
        parameters: '[{"keywords":["urgent","Urgent","Emergency"],"labels":["URGENT"]}]'

